In [2]:
import open3d as o3d
import numpy as np
import matplotlib.pyplot as plt
import os
import sys
import copy


In [4]:
pcd = o3d.io.read_point_cloud("data\ism_test_lioness.pcd")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

PointCloud with 3400 points.
[[-24.18340874 -53.01833725   2.42632174]
 [-24.3416729  -50.66685486   3.49008298]
 [-23.9833889  -50.21709824   6.07515764]
 ...
 [ 24.3416729  -50.66685486   3.49008298]
 [ 23.9833889  -50.21709824   6.07515764]
 [ 24.18340874 -53.01833725   2.42632174]]
